### PR TITLE
 #282: Don't let pyqt5 5.11.2 be used.

### PR DESCRIPTION
**Pull request by Julian-O**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I need @sccolbert to enable a webhook for appveyor so that it builds PRs. I will wait for him to do it before merging.

**Comment by MatthieuDartiailh** [comment]
@Julian-O Could you rebase on latest master ? I set up Appveyor webhook I would like to confirm it does work.

**Comment by Julian-O** [comment]
I am confused. There are no merge conflicts. There isn't an extensive list of commits to hide. [I am trying to avoid fighting with Git for an hour, when I don't know what I am trying to achieve.]

**Comment by MatthieuDartiailh** [comment]
I took the liberty to do it myself, I hope you don't mind. I just needed to see if appveyor was going to comment or not on the PR. Hopefully everything will pass.

**Pull request merged**
