### PR TITLE
Add more parser tests

### PR DESCRIPTION
**Pull request by frmdstryr**
Includes test for #266 

Also added test for a strange syntax error when using async def.

### CODE REVIEW

**Comment by frmdstryr** [comment]
Going to break into separate PR's

**Comment by frmdstryr** [comment]
@MatthieuDartiailh do you prefer the async tests go in a separate test module or should they be added to `test_function_definitions.py` and changed to use `validate_ast`?

**Comment by MatthieuDartiailh** [comment]
Before taking a decision, could you explain a bit more the context of those tests ? Since you are more focusing on the function body and in particular async/await stuff a new module dedicated to those may make sense.

**Comment by frmdstryr** [comment]
I'm building an analytics dashboard for a client using pandas, plotly, and enaml-web.  It loads data from a db using the await syntax. 

Something like

```python

async def fetch(view, request):
     # Build the query from request ...
     data = await db.fetch(query)
     # Load with pandas ...
     view.dataset = df

enamldef Page(BasePage):
    # Request handler checks if prepare exists and does  `await page.prepare(page, request)` 
    # then renders it and returns the result to the client
    attr prepare = fetch
    # Data
    attr dataset: pd.DataFrame
    # Rest of page does charts and stuff

```

In order to keep things organized, I want to put each view and related code in it's own separate enaml file.
It worked fine this way until I needed an `if` statement to build the query (hence the strange tests) so I currently have to push the fetching code into a separate py file and import it.  

It would be nice if the `func` keyword could be async so it's all encapsulated but this way works fine.

**Comment by MatthieuDartiailh** [comment]
Thanks for the background. 
To me it looks a bit like you are mixing model and view here, but I am not familiar with enaml-web. Since you are really testing that async/await code works as expected in enaml, a new file is probably better, but I would use validate_ast since if something is wrong it is the AST we build (after we just rely on the Python compiler).
Honestly I have no experience with async so I have no idea what it would cost to create a Declarative coroutine, but if you feel up to it feel free to try to get something together.

**Pull request closed without merging**
