### PR TITLE
widgets: add sync_time attribute to Field

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
@sccolbert this is one way to address #352 that seems minimally invasive. WDYT ?

### CODE REVIEW

**Comment by sccolbert** [comment]
This looks good to me, once it has coverage.

**Comment by MatthieuDartiailh** [comment]
Thanks @sccolbert . I need to deal with the fact that some old packages have been removed from conda main channel to get the CI to work. Do you want also specific tests for this functionality ? Currently the widgets are not properly tested but I was not planning to work on that before some time.

**Comment by sccolbert** [comment]
I was just commenting on the CI failures. I'm fine with the changes. Merge at your own discretion.

**Comment by MatthieuDartiailh** [comment]
Thanks !

**Pull request merged**
