### PR TITLE
Replace past/future with compat

### PR DESCRIPTION
**Pull request by frmdstryr**
Depends on the proposed changes for atom.

The `exec_` function was pulled from the `future` library the others are in the atom PR.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Thanks for your work @frmdstryr 
I am not sure why but the applib example test was skipped, which gives a large reduction in coverage. I will try to figure it out later, but feel free to beat me to it.

**Comment by frmdstryr** [comment]
Good now

**Comment by MatthieuDartiailh** [comment]
Thanks @frmdstryr for taking care of that. Originally I pinned pyqt 5 because 5.10 was crashing on Travis, but everything looks good now. Merging now and hopefully this will improve your start-up time.

**Comment by frmdstryr** [comment]
Thanks! Can you also tag a release for this and atom on github? 

No pypi release is needed, just need something [conda-mobile](https://github.com/codelv/conda-mobile) can reference (and I prefer not to use the master branch as it may change).

**Comment by MatthieuDartiailh** [comment]
If you really need this I can tag something like 0.10.3.a1, that does not entitle us to much.

**Comment by frmdstryr** [comment]
Yes that'd be fine. Also check the pre-release box to make it clear.

**Comment by MatthieuDartiailh** [comment]
Will do (but perhaps not today)

**Comment by MatthieuDartiailh** [comment]
I made the release.

**Comment by frmdstryr** [comment]
Thanks!

**Pull request merged**
