### PR TITLE
Add EnamlZipImporter

### LINKED ISSUE #115: with enaml.imports() support executing from .zip file (PEP 441)
I typically package up my python projects as .zip files so it's easy for other people to execute them. (See http://www.python.org/dev/peps/pep-0441/ )

It appears as though the "with enaml.imports()" feature does not support this at present. It would be a useful thing to add.

### PR DESCRIPTION
**Pull request by frmdstryr**
Fixes #115 

Includes test.

### CODE REVIEW

**Comment by sccolbert** [comment]
Awesome! I will review this ASAP. Thanks so much!

**Comment by frmdstryr** [comment]
Still has some issues with cache files... will reopen when i get some fixes

**Comment by MatthieuDartiailh** [comment]
Why closing ? I was about to have time to look at it.

**Comment by MatthieuDartiailh** [comment]
Could you rebase on master to fix the conflicts and get Travis working for this ?

**Comment by frmdstryr** [comment]
Closing this, everything is now in #232

**Pull request closed without merging**
