### PR TITLE
Add dock tab corner buttons

### PR DESCRIPTION
**Pull request by frmdstryr**
For #432 

This adds the QDockTitleBar as the corner widget to the QDockTabWidget with a new `tabs` button.

image

When the button is clicked it opens a context menu that lists all the tabs. When an action is clicked it sets that as the current tab.

image

It also keeps the close, maximize, and restore buttons.

The styling was messed up a little and I added some changes fix that. I'm not sure if that is specfic to my os.. Any help would be appreciated.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
This looks good. I will test locally in the coming days and comment again. One small question though since I am not extremely familiar with that part of the codebase: it looks like you had to add code to handle maximize/restore and close in the custom corner widget which was previously handled by the framework. Is there a way to avoid this by inheriting from the right Qt class that is used as default corner widget ?

**Comment by frmdstryr** [comment]
I don't think so... the tab widget seems to be treated like a layout similar to a splitter. I think the code was designed to only support maximizing a single dock item per area/window.  Maximizing a tab widget is more like maximizing a set of items.

Don't merge this yet as I think the way I'm restoring the layout needs changed.

Antother possible issue, I think this will not properly save and restore if maximized (I'm not using that so I didn't test it).

**Comment by MatthieuDartiailh** [comment]
I did give this a quick run and indeed the save/restore functionality appear to be broken in your branch, otherwise this seems pretty neat. Let me know if you need help with anything.

**Comment by frmdstryr** [comment]
Alright I think it's working properly now. The problem was when the tab widget was set to the maximize widget it was then no longer in the layout thus the layout saver wasn't including it. The "normal" way it works is the QDockContainer just passes the underlying QDockItem frame around (I think).

The workaround I used was to add a `QDockPlaceholder` that swaps itself with the tab widget and "saves it's place" in the dock layout when it's maximized and swaps back when restoring. Upon saving and building the layout it delegates to the widget it's holding the place for. 

There might be a cleaner way to do this, such as adding a `QDockWidgetContainer` which behaves similarly to the dock container. or something...

**Review by MatthieuDartiailh — APPROVED** [review]
This looks all good and works well locally. Ideally I would love to have some tests but I will merge as is for now.

Thanks for your contribution.

**Comment by frmdstryr** [comment]
Thanks!

**Pull request merged**
