### PR TITLE
Fix live_editor.enaml example for Qt5

### PR DESCRIPTION
**Pull request by frmdstryr**

### CODE REVIEW

**Comment by sccolbert** [comment]
Not sure this is the right fix for this.

**Comment by MatthieuDartiailh** [comment]
I am not a big fan of fixing the issue in this way. Also could you point to a way to get QScintilla packaged with PyQt5 such that I add this to the build matrix.

**Comment by frmdstryr** [comment]
Redid it in a proper way.  Also updated the test and travis.

I'm not sure why travis failed on 3.6, the errors seem unrelated.

**Comment by sccolbert** [comment]
Looks good to me. I'll let Matthieu make the call on the build script.

**Comment by MatthieuDartiailh** [comment]
Looks good to me. I will squash and merge and update the release notes. I will also increase the tests timeout to avoid the random failures on Travis. 
I will wait a month before cutting a new bugix release to see if people find other bugs in the new version.

**Pull request merged**
