### PR TITLE
Ensure some more QPoint values are ints

### PR DESCRIPTION
**Pull request by frmdstryr**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Looks good. Did you get a chance to audit other QPoint uses across the project ? If not I will try to do it. I would like for this PR to be the last regarding this issue.

**Comment by frmdstryr** [comment]
After getting an error from the first change I did a search for QPoint and these are the only ones I found.  It looks like most were done in #471

**Comment by MatthieuDartiailh** [comment]
Thanks for checking. Could add a release note entry (maybe just update the line of #471) ? I will merge ASAP.

**Comment by MatthieuDartiailh** [comment]
Thanks for checking. Could add a release note entry (maybe just update the line of #471) ? I will merge ASAP.

**Pull request merged**
