### PR TITLE
Fixes a couple of errors in the parser handling of function definition

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
One mistake was reported in #251, I found the other while debugging. @frmdstryr feel free to give a look and if you have an idea on how we could test this in clean way, I am very much interested.

### CODE REVIEW

**Comment by gabrielcnr** [comment]
@MatthieuDartiailh  I wrote a test for this which is probably closer to an integration test rather than a unit test because it tests the parser from a functional POV used with the compiler instead of making punctual assertions against AST types.

What do you think about the below:

```python
from enaml.core.parser import parse, write_tables
from enaml.core.enaml_compiler import EnamlCompiler
from future.utils import exec_


def test_p_varargslist18():
    write_tables()

    source = """
def func(foo=1, bar=2, **kwargs):
    d = {'foo': foo, 'bar': bar}
    d.update(kwargs)
    return d
"""

    ast = parse(source, filename='foo.enaml')
    code = EnamlCompiler.compile(ast, 'foo.enaml')

    ns = {}
    exec_(code, ns)

    func = ns['func']

    assert {'foo': 1, 'bar': 2} == func()

    assert {'foo': 100, 'bar': 200, 'spam': 300} == func(100, 200, spam=300)

```

**Comment by MatthieuDartiailh** [comment]
Thanks for your interest @gabrielcnr. Actually reading your proposed test gave me an idea for something that is believe is more robust and easier to automatize (based on ast analysis). I found a bunch of other issues running the tests actually. If you could take the time to read through the tests to check that I have not forgotten anything it would be great.

**Comment by frmdstryr** [comment]
Overall I'd say it looks good.   Is there a reason it's in a separate package? Took me a little to find it there...

The codecov report shows a few cases that are missing https://codecov.io/gh/nucleic/enaml/tree/e75c88e51ddd06daa0b31fde4dafeef503b22d1f/enaml/core/parser

**Comment by frmdstryr** [comment]
I added a few more cases here: https://github.com/MatthieuDartiailh/enaml/compare/parser_fixes...frmdstryr:parser_fixes?expand=1 but it only increases coverage by about 20 lines. 

The last two statements don't pass the ast check so IDK what's going on there.

**Comment by MatthieuDartiailh** [comment]
Thanks @frmdstryr. I put the tests in a different package because I usually try to follow the files organization for the tests organizations. So far we have little enough tests that it does not matter, but it is worth starting to clean up a bit.
I was also not planning to add total coverage of the parser in this PR (simply of the function definitions). If you are interested in adding more tests, feel free to open another pull request. I will merge this as is and look into the two cases that fail for you later.

**Pull request merged**
