### PR TITLE
Update test to reflect try/except Enaml issue

### PR DESCRIPTION
**Pull request by bburan**
This demonstrates #521

### CODE REVIEW

**Comment by sccolbert** [comment]
Ideally, this PR would include the fix, that way we don't break the build
unnecessarily.

**Comment by MatthieuDartiailh** [comment]
The underlying issue may lie in bytecode. I will try to have a look ASAP.

**Comment by MatthieuDartiailh** [comment]
@bburan can you try to reproduce using only bytecode ? And if you manage to do it report it to the bytecode repository.

**Comment by bburan** [comment]
Closing in favor of https://github.com/MatthieuDartiailh/bytecode/issues/118

**Pull request closed without merging**
