### PR TITLE
Flow Layout sort fix for stretch or ortho_stretch > 0

### PR DESCRIPTION
**Pull request by e-calder**
Potential fix for issue mentioned in https://github.com/nucleic/enaml/issues/447

```
<class 'TypeError'>
'<' not supported between instances of 'QFlowWidgetItem' and 'QFlowWidgetItem'

```

Dont rely on Python's sort; we should not include the QFlowWidgetItem in the sort key.

Disclaimer -  I had some issues running tests locally (had to start a whole new fresh python/venv environment but I'm not convinced I did it 100% correctly) so I *think* this test is OK.

### CODE REVIEW

**Review by sccolbert — APPROVED** [review]
This looks like a good fix to me. I did not review the test.

**Comment by MatthieuDartiailh** [comment]
Tests timed out on GHA but not appveyor. I will try to investigate in the coming days.

**Comment by MatthieuDartiailh** [comment]
I merged #442 that should help with CIs. Could you rebase your patch @e-calder ?

**Comment by MatthieuDartiailh** [comment]
Can you also add an entry to the release notes ? After that I think this will be good to go since the tests are fine.

**Pull request merged**
