### PR TITLE
Qt6 support

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
WIP on adding support for Qt6

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Apart from the appveyor failure this looks good but I did not test it on any large application yet. @bburan is Qt6 support something you are interested in ?

**Comment by bburan** [comment]
@MatthieuDartiailh I wasn't even aware that Qt had come out with a new major release! Looking at the end of life for Qt5, it looks like it's only a year out so I should think about testing this PR. I wouldn't be able to do so until March, most likely.

**Comment by MatthieuDartiailh** [comment]
No rush. You are one of the few person I am sure run a reasonably large app in Qt so I though it might be of interest.

**Comment by MatthieuDartiailh** [comment]
I am happy to report that https://github.com/Exopy/exopy works out of the box with Qt6. Since this is the largest application using the Qt backend I will merge this shortly. @bburan did you get a chance to test with your project ?

**Comment by MatthieuDartiailh** [comment]
The failure is related to recent support for PEP 621 in setuptools and a partially broken pyproject.toml at least in bytecode main. I will fix it ASAP.

**Comment by MatthieuDartiailh** [comment]
After fixing the condition under which the scintilla example is tested it looks all good. I will try to merge by the end of the week.

**Pull request merged**
