### PR TITLE
Add "Command Reference" to docs

### PR DESCRIPTION
**Pull request by frmdstryr**
For #344 .

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Looks good. I will probably extend the `enaml-run` documentation before merging (hopefully tonight). Thanks @frmdstryr

**Comment by MatthieuDartiailh** [comment]
@frmdstryr are you fine with my edits ? If yes I will merge ASAP.

**Comment by frmdstryr** [comment]
Should say "as follows" instead of "as follow". Other than that it looks good to me.

**Comment by MatthieuDartiailh** [comment]
Good catch thanks.

**Pull request merged**
