### PR TITLE
Support Python 3.8

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Python 3.8 introduced many changes to the bytecode. This PR will focus on addressing them and allow to run enaml on Python 3.8 using Python 3.7 syntax. New syntax introduced in Python 3.8 will be the focus of a different PR.

The first step (completed) towards supporting Python 3.8 is to switch from byteplay to bytecode (more modern interface and actively maintained) since Python 3.8 introduce once again many changes to the bytecode. 

The code requires ~https://github.com/vstinner/bytecode master~ bytecode 0.10.0 and pass all the tests on Python 3.8, 3.7 and 3.6. ~The next step is to adapt for Python 3.8.~

### CODE REVIEW

**Comment by frmdstryr** [comment]
Wow, thanks for all the work you've been doing on this!

**Comment by MatthieuDartiailh** [comment]
With bytecode 0.10.0 release out, this is ready from my point of view.

@frmdstryr @bburan since this is a fairly large change, it would be amazing if you could test things before merging.

**Comment by bburan** [comment]
@MatthieuDartiailh Thanks for bringing my attention to this and for your hard work! I will test over the next week and get back to you. A quick test showed a few incompatibilities that I need to fix in my code before it will run with the latest version of Enaml.

**Comment by frmdstryr** [comment]
Thanks, haven't had a chance to get to this yet. Will try to do it this weekend.

**Comment by MatthieuDartiailh** [comment]
I fixed one issue with importing (\_\_file\_\_ was not set) in #398 and rebased this PR.

**Comment by MatthieuDartiailh** [comment]
I tested locally against https://github.com/Exopy/exopy and fixed a couple of remaining issues for pyqt5 but got no python 3.8 related issues.

**Comment by MatthieuDartiailh** [comment]
Any update @bburan @frmdstryr ?

**Comment by bburan** [comment]
@MatthieuDartiailh Sorry, I've been totally swamped with other tasks at work. The main road-blocker for me is figuring out how to address a non-related change in Enaml (due to dropping of Python 2 compatibility). I have a function that relies on `enaml.core.import_hooks.EnamlImporter.load_module` to load an Enaml file stored in an arbitrary location on the filesystem:
```
from enaml.core import_hooks

def load_enaml_module_from_file(path):
    path = Path(path)
    name = path.with_suffix('').name
    file_info = import_hooks.make_file_info(str(path))
    importer = import_hooks.EnamlImporter(file_info)
    return importer.load_module(name)
```

The code can then be called, e.g.:

```
load_enaml_module_from_file('/home/bburan/.config/psiexperiment/plugins/IOManifest.enaml')
```
It seems `load_module` is no longer available, but I haven't had the chance to research it and this is preventing me from launching psiexperiment (the software that uses Enaml) to test your new branch. 

I'm not intimately familiar with Python's import machinery, so I'm sure my original approach was a hack and there are better ways to do it. If there's an obvious, simple solution or example somewhere please let me know. Otherwise, once I have a bit of time I'll take a closer look at it and see if I can resolve the import issue. Sorry for the delay in testing your branch.

**Comment by MatthieuDartiailh** [comment]
@bburan You could try something along the following lines inside an `enaml.imports` context (not tested but I will):
```python
import importlib.util
spec = importlib.util.spec_from_file_location("module.name", "/path/to/file.py")
foo = importlib.util.module_from_spec(spec)
spec.loader.exec_module(foo)
foo.MyClass()
```

**Comment by frmdstryr** [comment]
I just gave it a quick run with 3.8 and Inkcut and everything seems to be working fine.

**Comment by bburan** [comment]
@MatthieuDartiailh: Thanks for the tip. Seems that `importlib` is a bit strict about file extensions and still couldn't find the Enaml loader. But, I was able to get it working using this approach (assuming the module is `/home/lbhb/psi/io/ornitorinco.enaml`):
```
import importlib.util
from enaml.core import import_hooks

spec = import_hooks.EnamlImporter.find_spec('ornitorinco', path=['/home/lbhb/psi/io'])
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
print(module.IOManifest)
```

After that, everything works great with [psiexperiment](https://github.com/bburan/psiexperiment). I didn't encounter any issues. The software makes heavy use of Enaml's templating, workbench and dock area functionality. Let me know if there's anything specific you'd like me to test.

**Comment by MatthieuDartiailh** [comment]
Thanks @frmdstryr and @bburan (and sorry my example did not work). Given that every test we threw at this (including large dependent projects) has passed I will try to merge shortly.

**Pull request merged**
