### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by frmdstryr**
For #229 

Does anyone know where the vimeo video went? Would be nice to put that on youtube and link it here.

View it here https://github.com/frmdstryr/enaml/blob/786acb238d2c3c93ecb904cf173f302156f6ee4c/README.rst

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I have no idea where the vimeo video disappeared (never knew it existed). I like the README you propose but I will let @sccolbert take the final decision on this one.

**Comment by frmdstryr** [comment]
I sent PyData an email to see if they still have the video and can upload it to youtube. It's from this talk https://pydata.org/bos2013/abstracts/#70 (the title is wrong). 

Also, probably won't hear much from him this week (it's the week of thanksgiving in the US).

**Comment by frmdstryr** [comment]
Someone from PyData emailed back about a week ago and said they're working on moving the videos over from Vimeo to youtube so who knows if or when it'll happen.

**Comment by MatthieuDartiailh** [comment]
We can always add this video later. @sccolbert are you happy with this new version of the README ?

**Comment by MatthieuDartiailh** [comment]
ping @sccolbert

**Comment by MatthieuDartiailh** [comment]
This really looks like a nice improvement, so I am gonna merge. Thanks again @frmdstryr and let me know when the PyData video is online again.

**Pull request merged**
