### PR TITLE
qt: fix loading dock images

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
We test directly the loading since we cannot test D&D on the dock area

This is extremely annoying and I will do my best to release a patch version ASAP

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
ping @bburan since you worked on the previous patch

**Comment by frmdstryr** [comment]
I think the test is just accessing the member not triggering the factory?  It would be good to call the layout method to get a little coverage.

**Comment by MatthieuDartiailh** [comment]
I meant to access the guide on an instance... I added calls to layout

**Comment by bburan** [comment]
What is the bug here? The only fix I see is to get rid of the import for QDir?

**Comment by MatthieuDartiailh** [comment]
It has to do with the fact that we need a valid package for `path`. And without the extra `__init__` things were going really wrong.

**Comment by bburan** [comment]
@MatthieuDartiailh I see. For some odd reason I can't replicate the issue. On Python 3.9 at least it seems to automatically add a `__init__.py` file when installing to `site-packages`. Perhaps this bug is dependent on the version of setuptools? I've only just started learning about the new approach to Python packaging (i.e., putting everything in pyproject.toml).

Either case, I see no reason to hold off on this PR.

**Comment by bburan** [comment]
Just tested on a clean setup of Python 3.8 and I can replicate the bug. Applying this patch fixes the bug. Interesting. Probably a newer version of setuptools or setuptools_scm (that gets installed on Python 3.9) is smart enough to auto-create the `__init__.py` file? Either case, I can definitely confirm this patch fixes it.

**Comment by MatthieuDartiailh** [comment]
Thanks for testing thoroughly. I will merge and try to do a patch release ASAP.

**Pull request merged**
