### PR TITLE
fixed return value of QtWidget.tab_focus_request() and added release note entry

### PR DESCRIPTION
**Pull request by AndiEcker**
hope it will be PR 404

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Thanks since this is the second bug in the same region. I will try to add some tests to avoid future regression before merging.

**Comment by AndiEcker** [comment]
Thanks Matthieu - the new tests will be very helpful for me for to learn
how to also write some tests for the planned No-Focus implementation.

Am So., 5. Apr. 2020 um 20:30 Uhr schrieb Matthieu Dartiailh <
notifications@github.com>:

**Comment by MatthieuDartiailh** [comment]
I added tests that currently fails on Travis (not sure why) however I was unable to reproduce your issue locally. Since the change seems reasonable though I will probably merge as soon as the Cis are fine.

**Comment by MatthieuDartiailh** [comment]
Trying to kick Github actions

**Pull request merged**
